spring:
  application:
    name: chat
  data:
    mongodb:
      host: localhost
      port: 27018
      username: root
      password: testpassword1234
      database: mongodb
      authentication-database: admin
      authSource: admin

    redis:
      host: localhost
      port: 6379
      password: testpassword1234

server:
  port: 8081

auth:
  url: "http://localhost:8080/"
page:
  size: 100
invitation:
  expiration: 3600
