spring:
  application:
    name: chat
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27018
      username: root
      password: testpassword1234
      database: mongodb
      authentication-database: admin
      authSource: admin
      repositories:
        enabled: true

    redis:
      host: localhost
      port: 6379
      password: testpassword1234

server:
  port: 8081

auth:
  url: "http://localhost:30001/"
url:
  server: "${SERVER_SERVICE_URL:http://localhost:8080/}"
  front : "http://localhost:63342"

page:
  size: 100
chatroom:
  expiration: 1d
  baseurl: "http://localhost:8081/"

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging:
          simp: DEBUG
    root: INFO
    kpring.chat.chat.api.v1: DEBUG