spring:
  profiles:
    active: ${APPLICATION_PROFILE:local}
  application:
    name: user
  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:2435800}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/kpring}
  jpa:
    hibernate:
      ddl-auto: update

auth:
  url: ${AUTH_SERVICE_URL:http://localhost:8080/api/v1}
url:
  server: ${SERVER_SERVICE_URL:http://localhost:8080/}

file:
  path:
    profile-dir: /