spring:
  application:
    name: user
  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:2435800}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/kpring}
  jpa:
    hibernate:
      ddl-auto: update

auth:
  url: ${AUTH_SERVICE_URL:http://localhost:8080}

url:
  server: "http://localhost:8082"

server:
  port: 8081

file:
  path:
    profile-dir: /