spring:
  profiles:
    active: ${APPLICATION_PROFILE:local}
  application:
    name: server
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:test1234@}
      database: ${MONGO_DATABASE:mongodb}
      authentication-database: admin

auth:
  url: ${AUTH_SERVICE_URL:http://localhost:8080}

resource:
  default:
    profileImagePath: "todo" # todo
